description: Simple and flexible tool for managing secrets
downloadURLTemplate: https://github.com/getsops/{{.Name}}/releases/download/v{{.Version}}/{{.Name}}-v{{.Version}}.{{.OS}}.{{.Arch}}
homepage: https://github.com/getsops/sops
versionArgs: [--version]
